#!/bin/bash

even_sum=0
odd_sum=0

for var in "$@"
do  
    ./even $var && ((even_sum=even_sum+var))
    temp=$?
    if (( $temp == 1))
    then
        ((odd_sum=odd_sum+var))
    elif (( $temp == 3 ))
    then
        echo "Argumen $var is not a number"
        exit 1
    fi
    
done

echo sum of even numbers: $even_sum
echo sum of odd numbers: $odd_sum